Feat/ show inactive shifts in barista dashboard and modify delete shift logic
Neuroleptique/Barista-wanted pull request #21
Opened 2023-02-14 17:54 UTC by Neuroleptique

Question about this implementation:
- I actually implement 2 related features. Should the modification be divided into 2 separate PRs?

2023-02-16 14:00 UTC, WillowP commented
I do think you could have separated this into 2 PRs, since the 2 features are not really related in any way that I can see.

2023-02-16 14:03 UTC, WillowP requested changes
Added one minor code style comment. I think splitting this into 2 PRs is a good idea though :)

2023-02-16 14:03 UTC, WillowP commented on controllers/accounts.js
> +        const shiftPoster = activeShiftPoster.concat(pastShiftPoster)
I'm a little confused by these variable names. They are named as if they are single values or objects, but I think they are arrays. If so, I think just making the var names plural would help. Also you might consider renaming `shiftPoster` to `allShiftPosters` to be more expressive.

2023-02-18 02:05 UTC, Neuroleptique commented on controllers/accounts.js
> +        const shiftPoster = activeShiftPoster.concat(pastShiftPoster)
This change will be applied in Feat/baristaShowPastShift/new as I divide this PR into 2 separated PR.

2023-02-18 02:05 UTC, closed without merging